name: build_run_tests

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: update apt-get sources
        run: sudo apt-get update
      - name: install gcc-9
        run: sudo apt-get install -y gcc-9 g++-9 build-essential
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_C_COMPILER=gcc-9 ..
      - name: build
        run: cmake --build build --target testing-all
      - name: test
        run: cd build && ctest
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
      - name: build
        run: cmake --build build --target testing-all
      - name: test
        run: cd build && ctest
